### ISSUE TITLE
How does it work now with the input options?

### ISSUE THREAD

**Issue by NewtTheWolf** [OfficialDelta/TypeScript-Discord.js-v14-Template#5]
sorry to bother you again

How does it work now with the input options?

E.g.

```js
		.addStringOption((option) => {
			option.setName('message').setDescription('The message to reply with.');
		})
```

_Originally posted by @NewtTheWolf in https://github.com/TSLARoadster/TypeScript-Discord.js-v14-Template/issues/4#issuecomment-1221560512_

**Comment by TSLARoadster** [comment]
@NewtTheWolf I'm not sure I understand the problem. Could you elaborate? If possible have an entire code block example that I can replicate.

**Comment by rocketmay** [comment]
I'm having this issue too. Trying to add a new command using the template:

echo.ts

`import { SlashCommandBuilder } from 'discord.js'
import ApplicationCommand from '../templates/ApplicationCommand.js'

export default new ApplicationCommand({
    data: new SlashCommandBuilder()
        .setName('echo')
        .setDescription('Echoes the user input')
        .addStringOption(option => option.setName('input').setDescription('message to echo')), 
    
        async execute(interaction): Promise<void> {
        await interaction.reply(interaction.options.getString('echo',true))
    },
})
`

Getting an error: 
Type 'Omit<SlashCommandBuilder, "addSubcommand" | "addSubcommandGroup">' is not assignable to type 'SlashCommandBuilder | ContextMenuCommandBuilder | SlashCommandSubcommandsOnlyBuilder'.
  Type 'Omit<SlashCommandBuilder, "addSubcommand" | "addSubcommandGroup">' is missing the following properties from type 'SlashCommandBuilder': addSubcommandGroup, addSubcommand, _sharedAddOptionMethodts(2322)
ApplicationCommand.ts(29, 9): The expected type comes from property 'data' which is declared here on type '{ data: SlashCommandBuilder | ContextMenuCommandBuilder | SlashCommandSubcommandsOnlyBuilder; hasSubCommands?: boolean | undefined; execute?: ((interaction: ChatInputCommandInteraction<...>) => void | Promise<...>) | undefined; }'

**Comment by OfficialDelta** [comment]
Should be fixed now, sorry never got back to this.
