### ISSUE TITLE
Autocomplete?

### ISSUE THREAD

**Issue by menix1337** [OfficialDelta/TypeScript-Discord.js-v14-Template#95]
Hello there!

I'm not sure if you're still planning to update this package. I couldn't at least find this in your package!

DiscordJS also supports autocomplete in its slash commands, which requires a slight change to the commandHandler & ApplicationCommand.ts.
[Their docs for it here](https://discordjs.guide/slash-commands/autocomplete.html#enabling-autocomplete)

I'm not sure if this is something you might wanna look into implementing for a complete package? Or is this more or less done, as it is now?

I wish i could provide some sort of a PR; but I'm first starting to my bot now, used by a community with 45.000 members.
- And in that sense i noticed this wasn't built into your template

**Comment by menix1337** [comment]
Posted a PR - Works on my local test, however you might wanna check it through!

See #96 #

**Comment by OfficialDelta** [comment]
I can't believe someone actually noticed this repo haha, I actually made an autocomplete fix for my own bot but never updated the main repo, I'll push those changes in a little bit

**Comment by OfficialDelta** [comment]
Nevermind, your code is exactly the same as what I wrote lol, i'll merge your PR, thanks for contributing!
